name: Publish to npm on Main

on:
  push:
    branches:
      - main

jobs:
  release_and_publish:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - run: npm ci
      - run: npm test

      - name: Bump version and tag
        id: bump-version
        run: |
          npm version patch --no-git-tag-version
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add package.json package-lock.json
          git commit -m "CI: Bump version to $(node -p "require('./package.json').version")"
          git tag v$(node -p "require('./package.json').version")
          git push origin main --follow-tags
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
